#!/command/with-contenv bash

bootstrap_filesystems() {
    if ! [[ $(echo "${DATA_PATH}" | sed "s|/$||g") = "/app/data" ]] ; then
        rm -rf "/app/data/"
        ln -sf "${DATA_PATH}" /app/data/
        mkdir -p "${DATA_PATH}"
    fi
    mkdir -p "${DATA_PATH}"

    if [ "$(stat -c %U "${DATA_PATH}")" != "uptimekuma" ] ; then chown uptimekuma:uptimekuma "${DATA_PATH}" ; fi

    if [ "${LOG_TYPE,,}" = "both" ] || [ "${LOG_TYPE,,}" = "file" ] ; then
        if [ ! -d "${LOG_PATH}" ] ; then
            mkdir -p "${LOG_PATH}"
        fi
        if [ "$(stat -c %U "${LOG_PATH}")" != "uptimekuma" ] ; then chown uptimekuma:uptimekuma "${LOG_PATH}" ; fi
        create_logrotate uptimekuma "${LOG_PATH}"/"${LOG_FILE}" uptimekuma uptimekuma uptimekuma
    fi
}

configure_container() {
    update_template "/etc/nginx/sites.available/uptimekuma.conf" \
                                                                    LISTEN_PORT
}