#!/command/with-contenv bash

DATA_PATH=${DATA_PATH:-"/app/data/"}
LOG_FILE=${LOG_FILE:-"uptimekuma.log"}
LOG_PATH=${LOG_PATH:-"/logs/"}
LOG_TYPE=${LOG_TYPE:-"FILE"}
LISTEN_PORT=${LISTEN_PORT:-"3001"}